# quickstart.toml example
#
# Refer to https://github.com/jaynagpaul/qs/wiki/quickstart.toml
# for detailed Gopkg.toml documentation.

name = "Default QS Templates"

[[template]]
  TemplateFolder = "./license-qs" # This is not asked to the user.
  TemplateName = "License"    # This is not asked to the user.
  License = ["MIT", "Apache", "Creative Commons"]

[[template]]
  TemplateFolder = "./gitignore-qs" # This is not asked to the user.
  TemplateName = "Gitignore"    # This is not asked to the user.
  License = ["Go", "Javascript", "Python"]
  
